version: '3.7'

services:
  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build: ./SensorsDataWebApp
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  proxy:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  static:
  postgres_data:
